<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Attendance Report</title>
    <style>
        body {
            color: #111827;
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
            margin: 24px;
        }

        h1 {
            font-size: 20px;
            margin: 0 0 4px;
        }

        .muted {
            color: #6b7280;
        }

        .header {
            border-bottom: 1px solid #d1d5db;
            margin-bottom: 14px;
            padding-bottom: 12px;
        }

        .meta {
            margin-top: 8px;
            width: 100%;
        }

        .meta td {
            padding: 2px 0;
        }

        .summary {
            margin: 12px 0 14px;
            width: 100%;
        }

        .summary td {
            border: 1px solid #d1d5db;
            padding: 8px;
        }

        .summary .label {
            color: #6b7280;
            font-size: 9px;
            text-transform: uppercase;
        }

        .summary .value {
            font-size: 14px;
            font-weight: bold;
            margin-top: 2px;
        }

        table.records {
            border-collapse: collapse;
            width: 100%;
        }

        table.records th,
        table.records td {
            border: 1px solid #d1d5db;
            padding: 6px;
            vertical-align: middle;
        }

        table.records th {
            background: #f3f4f6;
            color: #374151;
            font-size: 9px;
            text-transform: uppercase;
        }

        .center {
            text-align: center;
        }

        .right {
            text-align: right;
        }

        .status {
            font-size: 9px;
            font-weight: bold;
            text-transform: uppercase;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Attendance Report</h1>
        <div class="muted">{{ $periodLabel }} | {{ $startDate->format('M d, Y') }} - {{ $endDate->format('M d, Y') }}</div>

        <table class="meta">
            <tr>
                <td><strong>Scope:</strong> {{ $scopeLabel }}</td>
                <td class="right"><strong>Generated:</strong> {{ $generatedAt->format('M d, Y h:i A') }}</td>
            </tr>
            <tr>
                <td><strong>Generated by:</strong> {{ $generatedBy }}</td>
                <td></td>
            </tr>
        </table>
    </div>

    <table class="summary">
        <tr>
            <td>
                <div class="label">Records</div>
                <div class="value">{{ number_format($summary['days']) }}</div>
            </td>
            <td>
                <div class="label">Hours</div>
                <div class="value">{{ number_format((float) $summary['hours'], 2) }}</div>
            </td>
            <td>
                <div class="label">Pending</div>
                <div class="value">{{ number_format($summary['pending']) }}</div>
            </td>
            <td>
                <div class="label">Approved</div>
                <div class="value">{{ number_format($summary['approved']) }}</div>
            </td>
            <td>
                <div class="label">Rejected</div>
                <div class="value">{{ number_format($summary['rejected']) }}</div>
            </td>
        </tr>
    </table>

    <table class="records">
        <thead>
            <tr>
                <th>Date</th>
                <th>Employee</th>
                <th>Type</th>
                <th>Time In</th>
                <th>Break 1</th>
                <th>Lunch</th>
                <th>Break 2</th>
                <th>Time Out</th>
                <th>Break</th>
                <th>Lunch</th>
                <th>Hours</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($attendances as $attendance)
                <tr>
                    <td>{{ $attendance->date->format('M d, Y') }}</td>
                    <td>{{ $attendance->employee_name ?: optional($attendance->user)->name }}</td>
                    <td class="center">{{ ucfirst($attendance->work_type ?? 'regular') }}</td>
                    <td class="center">{{ $attendance->time_in?->format('h:i A') ?? '-' }}</td>
                    <td class="center">
                        {{ $attendance->break_1_start?->format('h:i A') ?? '-' }}
                        @if($attendance->break_1_end) - {{ $attendance->break_1_end->format('h:i A') }} @endif
                    </td>
                    <td class="center">
                        {{ $attendance->lunch_start?->format('h:i A') ?? '-' }}
                        @if($attendance->lunch_end) - {{ $attendance->lunch_end->format('h:i A') }} @endif
                    </td>
                    <td class="center">
                        {{ $attendance->break_2_start?->format('h:i A') ?? '-' }}
                        @if($attendance->break_2_end) - {{ $attendance->break_2_end->format('h:i A') }} @endif
                    </td>
                    <td class="center">{{ $attendance->time_out?->format('h:i A') ?? '-' }}</td>
                    <td class="center">{{ $attendance->total_break_label }}</td>
                    <td class="center">{{ $attendance->total_lunch_label }}</td>
                    <td class="center">{{ number_format((float) $attendance->total_working_hours, 2) }}</td>
                    <td class="center status">{{ $attendance->status }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
</body>
</html>
