<?php

return [
    'modules' => [
        'for-me' => 'For Me', 'all-projects' => 'All Regular Services',
        'reports' => 'Reports', 'settings' => 'Regular Settings',
    ],
    'sections' => [
        'project-dashboard' => 'Dashboard',
        'work-order' => 'Work Order',
        'scope-of-work' => 'Scope of Work / RSAT',
        'review' => 'Review',
        'ntp' => 'NTP',
        'execution' => 'Execution',
        'files-evidence' => 'Files & Evidence',
        'time-aht' => 'Time & AHT',
        'client-actions' => 'Client Actions',
        'sow-report' => 'SOW / RSAT Report',
        'history-updates' => 'Updates & History',
        'delivery-completion' => 'Delivery & Completion',
    ],
    'project_sections' => [
        'project-dashboard' => 'Project Dashboard',
        'work-order' => 'Work Order',
        'scope-of-work' => 'Scope of Work',
        'review' => 'Review',
        'ntp' => 'NTP',
        'execution' => 'Execution',
        'files-evidence' => 'Files & Evidence',
        'time-aht' => 'Time & AHT',
        'client-actions' => 'Client Actions',
        'sow-report' => 'SOW Report',
        'history-updates' => 'Updates & History',
        'delivery-completion' => 'Delivery & Completion',
    ],
    'regular_sections' => [
        'project-dashboard' => 'Regular Dashboard',
        'work-order' => 'Work Order',
        'scope-of-work' => 'RSAT',
        'review' => 'Review',
        'ntp' => 'NTP',
        'execution' => 'Execution',
        'files-evidence' => 'Attachment',
        'time-aht' => 'Time & AHT',
        'client-actions' => 'Client Actions',
        'sow-report' => 'RSAT Report',
        'history-updates' => 'History',
        'delivery-completion' => 'Delivery & Completion',
    ],
    'hybrid_sections' => [
        'project-dashboard' => 'Hybrid Dashboard',
        'work-order' => 'Work Order',
        'scope-of-work' => 'Scope & RSAT',
        'review' => 'Review',
        'ntp' => 'NTP',
        'execution' => 'Execution',
        'files-evidence' => 'Files & Evidence',
        'time-aht' => 'Time & AHT',
        'client-actions' => 'Client Actions',
        'sow-report' => 'Engagement Report',
        'history-updates' => 'Updates & History',
        'delivery-completion' => 'Delivery & Completion',
    ],
    'projects' => [
        ['id' => 120, 'ref' => 'REG-2026-120', 'deal' => 'CONDEAL-2026-065', 'title' => 'Transfer of Share From Dany and Ronald to X10', 'business' => 'X10 REAL ESTATE CORPORATION', 'client' => 'May Flor D. Dabatos', 'stage' => 'Execution', 'progress' => 64, 'target' => 'Sep 18, 2026', 'health' => 'On Track', 'lead' => 'John Kelly Abalde'],
        ['id' => 119, 'ref' => 'REG-2026-119', 'deal' => 'CONDEAL-2026-066', 'title' => 'Transfer Shares Ronald to Stephan', 'business' => 'Individual', 'client' => 'Stephan Tenten', 'stage' => 'SOW', 'progress' => 18, 'target' => 'Sep 18, 2026', 'health' => 'On Track', 'lead' => 'Lyndon Earl Rio'],
        ['id' => 118, 'ref' => 'REG-2026-118', 'deal' => 'CONDEAL-2026-054', 'title' => 'Transfer Shares Mandaluyong and Makati', 'business' => 'Sanarex Med Group Inc.', 'client' => 'Doc Willy Dublin', 'stage' => 'Execution', 'progress' => 52, 'target' => 'Sep 11, 2026', 'health' => 'Needs Attention', 'lead' => 'John Kelly Abalde'],
        ['id' => 115, 'ref' => 'REG-2026-115', 'deal' => 'CONDEAL-2026-061', 'title' => 'SEC Registration', 'business' => 'Clear Path', 'client' => 'Chris Anderson', 'stage' => 'Reporting', 'progress' => 88, 'target' => 'Sep 11, 2026', 'health' => 'On Track', 'lead' => 'John Kelly Abalde'],
        ['id' => 113, 'ref' => 'REG-2026-113', 'deal' => 'CONDEAL-2026-034', 'title' => 'BIR and LGU Business Closure', 'business' => 'X10 REAL ESTATE CORPORATION', 'client' => 'X10', 'stage' => 'Execution', 'progress' => 48, 'target' => 'Sep 11, 2026', 'health' => 'At Risk', 'lead' => 'Lyndon Earl Rio'],
        ['id' => 110, 'ref' => 'REG-2026-110', 'deal' => 'CONDEAL-2026-036', 'title' => 'Tax Clearance', 'business' => 'Criminology Anti Crime Agency, Inc.', 'client' => 'Criminology Anti Crime Agency', 'stage' => 'Completed', 'progress' => 100, 'target' => 'Aug 07, 2026', 'health' => 'Completed', 'lead' => 'Lyndon Earl Rio'],
    ],
];
