<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class UserPermission extends Model
{
    protected $fillable = [
        'user_id',
        'manage_users',
        'create_user_account',
        'edit_user_account',
        'disable_enable_user_account',
        'reset_user_password',
        'delete_user_account',
        'access_admin_dashboard',
        'approve_townhall',
        'create_townhall',
        'create_corporate',
        'approve_corporate',
        'access_townhall',
        'access_corporate',
        'access_activities',
        'access_contacts',
        'access_company',
        'access_transmittal',
        'access_deals',
        'access_services',
        'access_project',
        'access_regular',
        'access_product',
        'access_policies',
        'create_sales_marketing',
        'approve_sales_marketing',
        'access_sales_marketing',
        'approve_policies',
        'access_human_capital',
        'access_hc_organizational',
        'access_hc_payroll',
        'access_hc_employee_profile',
        'access_hc_recruitment',
        'access_hc_onboarding',
        'access_hc_deployment',
        'access_hc_my_hc',
        'access_hc_attendance',
        'access_hc_obf',
        'access_hc_employee_requests',
        'access_hc_employee_relations',
        'access_hc_memos',
        'access_hc_training',
        'access_hc_performance',
        'access_hc_awards',
        'access_hc_offboarding',
        'access_finance',
        'create_finance',
        'approve_finance',
        'finance_treasurer',
        'finance_president',
        'finance_approver',
        'access_finance_supplier',
        'access_finance_service',
        'access_finance_product',
        'access_finance_chart_account',
        'access_finance_bank_account',
        'access_finance_pr',
        'access_finance_po',
        'access_finance_ca',
        'access_finance_lr',
        'access_finance_err',
        'access_finance_dv',
        'access_finance_pda',
        'access_finance_crf',
        'access_finance_ibtf',
        'access_finance_arf',
    ];
}
